### ISSUE TITLE
When running an external SVN diff, pre-existing temp files lead to runtime error

### ISSUE THREAD

**Issue by Wargazm** [facelessuser/EasyDiff#26]
steps to reproduce:

1. Open file that is checked into version control in Sublime
2. Right click on the tab, execute EasyDiff's SVN Diff command
    - Note that file myFileName-rBASE-LEFT.py is create in temp dir
3. External diff viewer opens as normal
4. Close external diff viewer
    - Note that file myFileName-rBASE-LEFT.py remains in temp directory
5. Execute SVN Diff command on same file
6. runtime error can be seen in log (copied/pasted below)

I think the fix is that EasyDiff needs to delete any pre-existing temp files when the command is executed, prior to calling the actual svn diff command.

Traceback below:

`
Traceback (most recent call last):
  File "easy_diff_version_control in <path to my portable sublime>\Data\Installed Packages\EasyDiff.sublime-package", line 161, in is_loaded
  File "easy_diff_version_control in <path to my portable sublime>\Data\Installed Packages\EasyDiff.sublime-package", line 182, in diff
  File "easy_diff_version_control in <path to my portable sublime>\Data\Installed Packages\EasyDiff.sublime-package", line 144, in external_diff
  File "easy_diff_version_control in <path to my portable sublime>\Data\Installed Packages\EasyDiff.sublime-package", line 275, in get_files
  File "lib.svn in <path to my portable sublime>\Data\Installed Packages\EasyDiff.sublime-package", line 231, in export
  File "lib.svn in <path to my portable sublime>\Data\Installed Packages\EasyDiff.sublime-package", line 63, in svnopen
AssertionError: Runtime Error: b"svn: E200009: Destination file '<path to my local appdata>\\Temp\\easydiff84zli9\\myFileName-rBASE-LEFT.py' exists, and will not be overwritten unless forced"
`

**Comment by facelessuser** [comment]
I'm not seeing this issue, but regardless, I think you are right in the sense that something better should be done. I think deleting is a bad idea though. There's no guarantee that we don't still have the file in question open. Instead, it would make sense to append a numerical value to the end which we increment if we see the file exists.

**Comment by Wargazm** [comment]
Yes, That is definitely a better idea!  

I'm not sure why the issue is happening to me.  I am using Beyond Compare 3, maybe that's part of it?  Not sure.  IN any case I do think making the temp file name more unique would help.

**Comment by facelessuser** [comment]
I thought the temp folder was unique each time, but it looks like it is the same throughout a sublime session?  Maybe day?  Not sure, but it keeps getting reused. We don't delete it either as we don't know when it is free to delete.  So a unique name is probably the way to go.  I use Beyond Compare 4, but I don't recall this issue with 3...but who knows.  Regardless, this is an oversight on my part that should be corrected.

**Comment by facelessuser** [comment]
Changes are now on master.  I'll cut a release tonight.
